import React,{useState,useEffect,useMemo}from 'react'
import{PieChart,Pie,Cell,ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,BarChart,Bar}from 'recharts'
const IS=[{id:'s1',name:'Mentoria Calistenia',value:150,currency:'BRL',category:'Desenvolvimento',active:true},{id:'s2',name:'Mentoria Vestibular',value:350,currency:'BRL',category:'Desenvolvimento',active:true},{id:'s3',name:'Claude Pro',value:110,currency:'BRL',category:'Ferramentas IA',active:true},{id:'s4',name:'Supernotes',value:54,currency:'BRL',category:'Ferramentas',active:true},{id:'s5',name:'Notion Business',value:30,currency:'USD',category:'Ferramentas IA',active:true},{id:'s6',name:'TickTick',value:4,currency:'USD',category:'Ferramentas',active:true},{id:'s7',name:'Wispr Flow',value:30,currency:'BRL',category:'Ferramentas IA',active:true},{id:'s8',name:'Comunidade IA',value:97,currency:'BRL',category:'Desenvolvimento',active:false}]
const I0={income:1090,vr:330,vrTablet:200,vrMesada:50,creditLimit:600,exchangeRate:5.70,exchangeLastUpdated:null,subs:IS,transactions:[],creditTransactions:[],reserveBox:0,cdiRate:10.5}
const f=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:0,maximumFractionDigits:0}).format(v||0)
const f2=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2}).format(v||0)
const uid=()=>Math.random().toString(36).slice(2,9)
const CC={'Desenvolvimento':'#DC2626','Ferramentas IA':'#D4A84B','Ferramentas':'#737373','Alimentacao':'#22C55E','Lazer':'#8B5CF6','Transporte':'#3B82F6','Outros':'#525252'}
const HL=['CRITICO','RISCO','ATENCAO','SAUDAVEL','EXCELENTE']
const HC=['#DC2626','#F97316','#EAB308','#22C55E','#10B981']
export default function NexusFinance(){
  const[state,setState]=useState(I0)
  const[tab,setTab]=useState('macro')
  const[showTx,setShowTx]=useState(false)
  const[showCC,setShowCC]=useState(false)
  const[showSub,setShowSub]=useState(false)
  const[txF,setTxF]=useState({desc:'',value:'',cat:'Alimentacao',date:new Date().toISOString().slice(0,10)})
  const[ccF,setCcF]=useState({desc:'',value:'',installments:1,date:new Date().toISOString().slice(0,10)})
  const[subF,setSubF]=useState({name:'',value:'',currency:'BRL',category:'Ferramentas'})
  const[ai,setAi]=useState('')
  const[aiL,setAiL]=useState(false)
  const[loaded,setLoaded]=useState(false)
  const[toast,setToast]=useState(null)
  useEffect(()=>{try{const r=localStorage.getItem('nfv2');if(r)setState(p=>({...p,...JSON.parse(r)}))}catch(e){};setLoaded(true)},[])
  useEffect(()=>{if(!loaded)return;try{localStorage.setItem('nfv2',JSON.stringify(state))}catch(e){}},[state,loaded])
  const notify=m=>{setToast(m);setTimeout(()=>setToast(null),2500)}
  useEffect(()=>{const go=async()=>{try{const r=await fetch('https://api.frankfurter.app/latest?from=USD&to=BRL');const d=await r.json();const x=d?.rates?.BRL;if(x&&!isNaN(x))setState(p=>({...p,exchangeRate:parseFloat(x.toFixed(4)),exchangeLastUpdated:new Date().toISOString()}))}catch(e){}};go();const iv=setInterval(go,6*60*60*1000);return()=>clearInterval(iv)},[])
  const subs=useMemo(()=>state.subs.filter(s=>s.active).reduce((a,s)=>a+(s.currency==='USD'?s.value*state.exchangeRate:s.value),0),[state.subs,state.exchangeRate])
  const vrL=state.vr-state.vrTablet-state.vrMesada
  const mk=`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}`
  const txM=state.transactions.filter(t=>t.date&&t.date.startsWith(mk))
  const txT=txM.reduce((a,t)=>a+t.value,0)
  const saldo=state.income-subs-txT
  const ccU=state.creditTransactions.reduce((a,t)=>a+t.value/t.installments,0)
  const ccA=state.creditLimit-ccU
  const mY=state.reserveBox*state.cdiRate/100/12
  const burn=useMemo(()=>{const d=new Date().getDate();const dm=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate();const sp=subs+txT;return{daily:sp/(d+1),daysLeft:dm-d}},[subs,txT])
  const hs=useMemo(()=>{let s=50;const sr=saldo/state.income;if(sr>0.2)s+=20;else if(sr>0.1)s+=10;else if(sr>0)s+=5;else s-=20;if(state.creditTransactions.length===0)s+=15;else if(ccU/state.creditLimit<0.3)s+=15;else if(ccU/state.creditLimit>0.7)s+=5;else s-=15;if(subs/state.income<0.7)s+=10;else s-=10;if(state.reserveBox>0)s+=5;return Math.max(0,Math.min(100,s))},[saldo,state.income,ccU,state.creditLimit,subs,state.reserveBox,state.creditTransactions.length])
  const hi=hs>=80?4:hs>=65?3:hs>=45?2:hs>=25?1:0
  const cats=useMemo(()=>{const m={};state.subs.filter(s=>s.active).forEach(s=>{const v=s.currency==='USD'?s.value*state.exchangeRate:s.value;m[s.category]=(m[s.category]||0)+v});txM.forEach(t=>{m[t.cat]=(m[t.cat]||0)+t.value});return Object.entries(m).map(([name,value])=>({name,value:Math.round(value)})).sort((a,b)=>b.value-a.value)},[state.subs,state.transactions,state.exchangeRate])
  const proj=useMemo(()=>{const ms=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];const cm=new Date().getMonth();return Array.from({length:6},(_,i)=>{const m=(cm+i)%12;const e=i>=3?200*(i-2):0;return{name:ms[m],renda:state.income+e,gastos:subs,livre:state.income+e-subs}})},[state.income,subs])
  const addTx=()=>{if(!txF.desc||!txF.value)return;setState(p=>({...p,transactions:[...p.transactions,{id:uid(),desc:txF.desc,value:parseFloat(txF.value),cat:txF.cat,date:txF.date}]}));setTxF({desc:'',value:'',cat:'Alimentacao',date:new Date().toISOString().slice(0,10)});setShowTx(false);notify('Gasto registrado')}
  const addCC=()=>{if(!ccF.desc||!ccF.value)return;const v=parseFloat(ccF.value);setState(p=>({...p,creditTransactions:[...p.creditTransactions,{id:uid(),desc:ccF.desc,value:v,installments:parseInt(ccF.installments)||1,date:ccF.date,paidInstallments:0}],reserveBox:p.reserveBox+v/(parseInt(ccF.installments)||1)}));setCcF({desc:'',value:'',installments:1,date:new Date().toISOString().slice(0,10)});setShowCC(false);notify('Compra registrada')}
  const addSub=()=>{if(!subF.name||!subF.value)return;setState(p=>({...p,subs:[...p.subs,{id:uid(),name:subF.name,value:parseFloat(subF.value),currency:subF.currency,category:subF.category,active:true}]}));setSubF({name:'',value:'',currency:'BRL',category:'Ferramentas'});setShowSub(false);notify('Assinatura adicionada')}
  const togSub=id=>setState(p=>({...p,subs:p.subs.map(s=>s.id===id?{...s,active:!s.active}:s)}))
  const delTx=id=>setState(p=>({...p,transactions:p.transactions.filter(t=>t.id!==id)}))
  const delCC=id=>setState(p=>({...p,creditTransactions:p.creditTransactions.filter(t=>t.id!==id)}))
  const delSub=id=>setState(p=>({...p,subs:p.subs.filter(s=>s.id!==id)}))
const S={root:{fontFamily:"'Sora',sans-serif",background:'#09090B',color:'#E4E4E7',minHeight:'100vh',padding:0,margin:0,fontSize:13},header:{padding:'24px 28px 16px',borderBottom:'1px solid rgba(212,168,75,0.12)',display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:12},logo:{display:'flex',alignItems:'center',gap:10},logoI:{width:32,height:32,borderRadius:8,background:'linear-gradient(135deg,#DC2626,#D4A84B)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:16,fontWeight:800,color:'#09090B'},logoT:{fontSize:18,fontWeight:700,letterSpacing:'-0.03em',background:'linear-gradient(90deg,#DC2626,#D4A84B)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'},tabs:{display:'flex',gap:2,background:'#18181B',borderRadius:10,padding:3},tab:a=>({padding:'8px 16px',borderRadius:8,border:'none',cursor:'pointer',fontSize:12,fontWeight:a?600:400,fontFamily:'inherit',color:a?'#09090B':'#71717A',background:a?'linear-gradient(135deg,#DC2626,#D4A84B)':'transparent'}),main:{padding:'20px 28px 40px'},g:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:14},g2:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,marginTop:20},c:{background:'#18181B',borderRadius:14,padding:'18px 20px',border:'1px solid #27272A'},cg:x=>({background:'#18181B',borderRadius:14,padding:'18px 20px',border:`1px solid ${x}22`,boxShadow:`0 0 30px ${x}08`}),lbl:{fontSize:10,fontWeight:500,textTransform:'uppercase',letterSpacing:'0.08em',color:'#71717A',marginBottom:6},v:{fontSize:24,fontWeight:700,letterSpacing:'-0.03em'},vs:{fontSize:18,fontWeight:600},btn:{padding:'10px 20px',borderRadius:10,border:'none',cursor:'pointer',fontSize:12,fontWeight:600,fontFamily:'inherit',background:'linear-gradient(135deg,#DC2626,#D4A84B)',color:'#09090B'},bg:{padding:'10px 20px',borderRadius:10,border:'1px solid #27272A',cursor:'pointer',fontSize:12,fontFamily:'inherit',background:'transparent',color:'#A1A1AA'},inp:{padding:'10px 14px',borderRadius:10,border:'1px solid #27272A',background:'#09090B',color:'#E4E4E7',fontSize:13,fontFamily:'inherit',width:'100%',boxSizing:'border-box',outline:'none'},sel:{padding:'10px 14px',borderRadius:10,border:'1px solid #27272A',background:'#09090B',color:'#E4E4E7',fontSize:13,fontFamily:'inherit',width:'100%',boxSizing:'border-box',outline:'none'},modal:{position:'fixed',inset:0,background:'rgba(0,0,0,0.75)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:999,backdropFilter:'blur(8px)'},mbox:{background:'#18181B',borderRadius:18,padding:28,width:'min(90vw,400px)',border:'1px solid #27272A'},toast:{position:'fixed',bottom:24,left:'50%',transform:'translateX(-50%)',background:'#D4A84B',color:'#09090B',padding:'10px 24px',borderRadius:10,fontSize:13,fontWeight:600,fontFamily:'inherit',zIndex:9999}}
const TT=({active,payload,label})=>{if(!active||!payload?.length)return null;return<div style={{background:'#18181B',border:'1px solid #27272A',borderRadius:10,padding:'10px 14px',fontSize:12}}><div style={{color:'#71717A',marginBottom:4}}>{label}</div>{payload.map((p,i)=><div key={i} style={{color:p.color}}>{p.name}: {f(p.value)}</div>)}</div>}
const Ring=({score})=>{const r=54,c=2*Math.PI*r,o=c*(1-score/100);return<svg width={120} height={120} style={{transform:'rotate(-90deg)'}}><circle cx={60} cy={60} r={r} fill="none" stroke="#27272A" strokeWidth={6}/><circle cx={60} cy={60} r={r} fill="none" stroke={HC[hi]} strokeWidth={6} strokeDasharray={c} strokeDashoffset={o} strokeLinecap="round" style={{transition:'stroke-dashoffset 1s'}}/><text x={60} y={60} textAnchor="middle" dominantBaseline="central" fill={HC[hi]} fontSize={28} fontWeight={800} style={{transform:'rotate(90deg)',transformOrigin:'center'}}>{score}</text></svg>}
const Macro=()=><div><div style={S.g}><div style={S.cg('#D4A84B')}><div style={S.lbl}>Saldo Livre</div><div style={{...S.v,color:saldo>=0?'#D4A84B':'#DC2626'}}>{f(saldo)}</div><div style={{fontSize:11,color:'#71717A',marginTop:4}}>de {f(state.income)}</div></div><div style={S.cg('#DC2626')}><div style={S.lbl}>Comprometido Fixo</div><div style={{...S.v,color:'#DC2626'}}>{f(subs)}</div><div style={{fontSize:11,color:'#71717A',marginTop:4}}>{Math.round(subs/state.income*100)}% da renda</div></div><div style={S.c}><div style={S.lbl}>VR Disponivel</div><div style={{...S.v,color:vrL>=0?'#22C55E':'#DC2626'}}>{f(vrL)}</div><div style={{fontSize:11,color:'#71717A',marginTop:4}}>de {f(state.vr)}</div></div><div style={S.c}><div style={S.lbl}>Burn Rate Diario</div><div style={{...S.vs,color:'#E4E4E7'}}>{f2(burn.daily)}<span style={{fontSize:11,color:'#71717A'}}>/dia</span></div><div style={{fontSize:11,color:'#71717A',marginTop:4}}>{burn.daysLeft}d restantes</div></div></div><div style={S.g2}><div style={{...S.c,display:'flex',flexDirection:'column',alignItems:'center',padding:'28px 20px'}}><div style={S.lbl}>Score de Saude Financeira</div><div style={{margin:'12px 0'}}><Ring score={hs}/></div><div style={{display:'inline-block',padding:'4px 14px',borderRadius:6,fontSize:12,fontWeight:600,background:`${HC[hi]}18`,color:HC[hi]}}>{HL[hi]}</div><div style={{fontSize:11,color:'#71717A',marginTop:12,textAlign:'center'}}>{hs>=65?'Situacao controlada.':'Margem apertada.'}</div></div><div style={S.c}><div style={S.lbl}>Projecao 6 Meses</div><ResponsiveContainer width="100%" height={180}><AreaChart data={proj} margin={{top:10,right:10,left:-20,bottom:0}}><defs><linearGradient id="gL" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#D4A84B" stopOpacity={0.3}/><stop offset="100%" stopColor="#D4A84B" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="name" tick={{fill:'#71717A',fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'#71717A',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip content={<TT/>}/><Area type="monotone" dataKey="renda" stroke="#22C55E" strokeWidth={1.5} fillOpacity={0} dot={false} name="Renda"/><Area type="monotone" dataKey="livre" stroke="#D4A84B" strokeWidth={2} fill="url(#gL)" dot={false} name="Livre"/></AreaChart></ResponsiveContainer></div></div></div>
const Meso=()=><div><div style={S.g2}><div style={S.c}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div style={S.lbl}>Assinaturas</div><button style={{...S.btn,padding:'6px 14px',fontSize:11}} onClick={()=>setShowSub(true)}>Nova</button></div>{state.subs.map(s=>{const v=s.currency==='USD'?s.value*state.exchangeRate:s.value;return<div key={s.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid #1E1E22'}}><div style={{display:'flex',alignItems:'center',gap:10,flex:1}}><div onClick={()=>togSub(s.id)} style={{width:18,height:18,borderRadius:5,border:`2px solid ${s.active?'#D4A84B':'#3F3F46'}`,background:s.active?'#D4A84B18':'transparent',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',fontSize:10,color:'#D4A84B'}}>{s.active?'✓':''}</div><div><div style={{fontSize:13,fontWeight:500,opacity:s.active?1:0.4,textDecoration:s.active?'none':'line-through'}}>{s.name}</div><div style={{fontSize:10,color:'#52525B'}}>{s.category}</div></div></div><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{fontWeight:600,color:s.active?'#E4E4E7':'#52525B'}}>{f(v)}</span><button onClick={()=>delSub(s.id)} style={{background:'none',border:'none',color:'#3F3F46',cursor:'pointer',fontSize:14}}>×</button></div></div>})}<div style={{marginTop:14,padding:'12px 16px',borderRadius:10,background:'#DC262610',border:'1px solid #DC262620'}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:12,fontWeight:600,color:'#DC2626'}}>Total</span><span style={{fontSize:14,fontWeight:700,color:'#DC2626'}}>{f(subs)}</span></div><div style={{fontSize:10,color:'#71717A',marginTop:4}}>{Math.round(subs/state.income*100)}% da renda · R${state.exchangeRate.toFixed(4)}/USD</div></div></div><div style={S.c}><div style={S.lbl}>Por Categoria</div><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={cats} cx="50%" cy="50%" innerRadius={50} outerRadius={80} paddingAngle={3} dataKey="value">{cats.map((e,i)=><Cell key={i} fill={CC[e.name]||HC[i%5]}/>)}</Pie><Tooltip content={({active,payload})=>active&&payload?.length?<div style={{background:'#18181B',border:'1px solid #27272A',borderRadius:8,padding:'8px 12px',fontSize:12}}>{payload[0].name}: {f(payload[0].value)}</div>:null}/></PieChart></ResponsiveContainer><div style={{display:'flex',flexWrap:'wrap',gap:8,marginTop:8}}>{cats.map((c,i)=><div key={i} style={{display:'flex',alignItems:'center',gap:4,fontSize:10}}><div style={{width:8,height:8,borderRadius:2,background:CC[c.name]||HC[i%5]}}/><span style={{color:'#A1A1AA'}}>{c.name}</span></div>)}</div></div></div></div>
const Micro=()=><div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><div style={S.lbl}>Gastos do Mes</div><div style={{...S.vs,color:txT>0?'#DC2626':'#71717A'}}>{f(txT)}</div></div><button style={S.btn} onClick={()=>setShowTx(true)}>Registrar</button></div>{txM.length===0?<div style={{...S.c,textAlign:'center',padding:'40px 20px',color:'#3F3F46'}}><div style={{fontSize:32,marginBottom:8}}>0</div><div>Nenhum gasto registrado</div></div>:<div style={S.c}>{txM.slice().sort((a,b)=>b.date?.localeCompare(a.date)).map(t=><div key={t.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid #1E1E22'}}><div><div style={{fontSize:13,fontWeight:500}}>{t.desc}</div><div style={{fontSize:10,color:'#52525B'}}>{t.cat} · {new Date(t.date+'T12:00').toLocaleDateString('pt-BR')}</div></div><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{fontWeight:600,color:'#DC2626'}}>-{f(t.value)}</span><button onClick={()=>delTx(t.id)} style={{background:'none',border:'none',color:'#3F3F46',cursor:'pointer',fontSize:14}}>×</button></div></div>)}</div>}</div>
const Cartao=()=><div><div style={S.g}><div style={S.cg('#6366F1')}><div style={S.lbl}>Limite Disponivel</div><div style={{...S.v,color:ccA>100?'#6366F1':'#DC2626'}}>{f(ccA)}</div><div style={{height:6,borderRadius:3,background:'#27272A',overflow:'hidden',marginTop:8}}><div style={{height:'100%',borderRadius:3,width:`${Math.min(ccU/state.creditLimit*100,100)}%`,background:ccU/state.creditLimit>0.9?'#DC2626':'#6366F1',transition:'width 0.5s'}}/></div><div style={{fontSize:10,color:'#71717A',marginTop:6}}>{f(ccU)} usado de {f(state.creditLimit)}</div></div><div style={S.cg('#D4A84B')}><div style={S.lbl}>Caixa Reserva</div><div style={{...S.v,color:'#D4A84B'}}>{f(state.reserveBox)}</div><div style={{fontSize:11,color:'#22C55E',marginTop:4}}>{f2(mY)}/mes rendendo</div></div><div style={S.c}><div style={S.lbl}>Limite do Cartao</div><input type="number" value={state.creditLimit} onChange={e=>setState(p=>({...p,creditLimit:parseFloat(e.target.value)||600}))} style={{...S.inp,fontSize:18,fontWeight:700}}/></div></div><div style={{...S.c,marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><div style={S.lbl}>Compras no Credito</div><button style={{...S.btn,padding:'6px 14px',fontSize:11}} onClick={()=>setShowCC(true)}>Compra</button></div>{state.creditTransactions.length===0?<div style={{textAlign:'center',padding:'30px 20px',color:'#3F3F46',fontSize:12}}>Nenhuma compra</div>:state.creditTransactions.map(t=><div key={t.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid #1E1E22'}}><div><div style={{fontSize:13,fontWeight:500}}>{t.desc}</div><div style={{fontSize:10,color:'#52525B'}}>{t.installments}x de {f(t.value/t.installments)}</div></div><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{fontWeight:600,color:'#6366F1'}}>{f(t.value)}</span><button onClick={()=>delCC(t.id)} style={{background:'none',border:'none',color:'#3F3F46',cursor:'pointer',fontSize:14}}>×</button></div></div>)}</div></div>
return<div style={S.root}><style>{`@import url('https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700;800&display=swap');*{box-sizing:border-box;margin:0;padding:0}input:focus,select:focus{border-color:#D4A84B!important}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-thumb{background:#27272A;border-radius:2px}`}</style><header style={S.header}><div style={S.logo}><div style={S.logoI}>N</div><span style={S.logoT}>NEXUS FINANCE</span></div><nav style={S.tabs}>{[['macro','MACRO'],['meso','MESO'],['micro','MICRO'],['cartao','CARTAO']].map(([k,v])=><button key={k} style={S.tab(tab===k)} onClick={()=>setTab(k)}>{v}</button>)}</nav></header><main style={S.main}>{tab==='macro'&&<Macro/>}{tab==='meso'&&<Meso/>}{tab==='micro'&&<Micro/>}{tab==='cartao'&&<Cartao/>}</main>
{showTx&&<div style={S.modal} onClick={()=>setShowTx(false)}><div style={S.mbox} onClick={e=>e.stopPropagation()}><div style={{fontSize:16,fontWeight:700,marginBottom:20}}>Registrar Gasto</div><div style={{display:'flex',flexDirection:'column',gap:12}}><input placeholder="Descricao" value={txF.desc} onChange={e=>setTxF(p=>({...p,desc:e.target.value}))} style={S.inp}/><input type="number" placeholder="Valor R$" value={txF.value} onChange={e=>setTxF(p=>({...p,value:e.target.value}))} style={S.inp}/><select value={txF.cat} onChange={e=>setTxF(p=>({...p,cat:e.target.value}))} style={S.sel}>{['Alimentacao','Lazer','Transporte','Desenvolvimento','Ferramentas','Outros'].map(c=><option key={c}>{c}</option>)}</select><input type="date" value={txF.date} onChange={e=>setTxF(p=>({...p,date:e.target.value}))} style={S.inp}/><div style={{display:'flex',gap:10,marginTop:8}}><button style={S.btn} onClick={addTx}>Salvar</button><button style={S.bg} onClick={()=>setShowTx(false)}>Cancelar</button></div></div></div></div>}
{showCC&&<div style={S.modal} onClick={()=>setShowCC(false)}><div style={S.mbox} onClick={e=>e.stopPropagation()}><div style={{fontSize:16,fontWeight:700,marginBottom:20}}>Compra no Credito</div><div style={{display:'flex',flexDirection:'column',gap:12}}><input placeholder="Descricao" value={ccF.desc} onChange={e=>setCcF(p=>({...p,desc:e.target.value}))} style={S.inp}/><input type="number" placeholder="Valor total" value={ccF.value} onChange={e=>setCcF(p=>({...p,value:e.target.value}))} style={S.inp}/><input type="number" placeholder="Parcelas" value={ccF.installments} min={1} max={12} onChange={e=>setCcF(p=>({...p,installments:e.target.value}))} style={S.inp}/><input type="date" value={ccF.date} onChange={e=>setCcF(p=>({...p,date:e.target.value}))} style={S.inp}/>{ccF.value&&ccF.installments&&<div style={{padding:'10px 14px',borderRadius:8,background:'#D4A84B10',fontSize:11,color:'#D4A84B'}}>Parcela: {f(parseFloat(ccF.value)/(parseInt(ccF.installments)||1))}</div>}<div style={{display:'flex',gap:10,marginTop:8}}><button style={S.btn} onClick={addCC}>Registrar</button><button style={S.bg} onClick={()=>setShowCC(false)}>Cancelar</button></div></div></div></div>}
{showSub&&<div style={S.modal} onClick={()=>setShowSub(false)}><div style={S.mbox} onClick={e=>e.stopPropagation()}><div style={{fontSize:16,fontWeight:700,marginBottom:20}}>Nova Assinatura</div><div style={{display:'flex',flexDirection:'column',gap:12}}><input placeholder="Nome" value={subF.name} onChange={e=>setSubF(p=>({...p,name:e.target.value}))} style={S.inp}/><input type="number" placeholder="Valor" value={subF.value} onChange={e=>setSubF(p=>({...p,value:e.target.value}))} style={S.inp}/><select value={subF.currency} onChange={e=>setSubF(p=>({...p,currency:e.target.value}))} style={S.sel}><option value="BRL">R$ BRL</option><option value="USD">USD</option></select><select value={subF.category} onChange={e=>setSubF(p=>({...p,category:e.target.value}))} style={S.sel}>{['Ferramentas','Ferramentas IA','Desenvolvimento','Lazer','Outros'].map(c=><option key={c}>{c}</option>)}</select><div style={{display:'flex',gap:10,marginTop:8}}><button style={S.btn} onClick={addSub}>Adicionar</button><button style={S.bg} onClick={()=>setShowSub(false)}>Cancelar</button></div></div></div></div>}
{toast&&<div style={S.toast}>{toast}</div>}</div>}
  